# Generated by Django 2.2.3 on 2019-08-14 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('improve', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='video',
            field=models.TextField(),
        ),
    ]
