# Generated by Django 2.2.3 on 2019-08-19 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='fav_book',
            field=models.CharField(blank=True, choices=[('first book', 'first book'), ('Book Two', 'Book Two'), ('Book Second', 'Book Second'), ('Book 0', 'Book 0'), ('Book 1', 'Book 1'), ('Book 2', 'Book 2'), ('Book 3', 'Book 3')], max_length=100, null=True),
        ),
    ]
