# Generated by Django 2.2.3 on 2019-08-20 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20190819_1645'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavBooks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fav_book', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='fav_book',
        ),
        migrations.AddField(
            model_name='profile',
            name='fav_book',
            field=models.ManyToManyField(blank=True, choices=[('first book', 'first book'), ('Book Two', 'Book Two'), ('Book Second', 'Book Second'), ('Book 0', 'Book 0'), ('Book 1', 'Book 1'), ('Book 2', 'Book 2'), ('Book 3', 'Book 3')], null=True, to='catalog.FavBooks'),
        ),
    ]
