# Generated by Django 2.2.3 on 2019-08-20 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20190820_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='fav_book',
            field=models.ManyToManyField(blank=True, null=True, to='catalog.FavBooks'),
        ),
    ]
