# Generated by Django 2.2.3 on 2019-08-07 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20190807_0606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(help_text='Select a genre for this book', null=True, to='catalog.Genre'),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(default='books/temp.jpg', null=True, upload_to='books/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='summary',
            field=models.TextField(help_text='Enter a brief description of the book', max_length=1000, null=True),
        ),
    ]
